### ISSUE TITLE
Проблема с информацией, указываемой в Privacy manifest для ios

### ISSUE THREAD

**Issue by lighthead9288** [appmetrica/appmetrica-flutter-plugin#2]
Добрый день! Используем appmetrica_plugin версии 2.1.1 - после публикации приложения в AppStore получаем письмо следующего содержания:

>
We noticed one or more issues with a recent submission for App Store review for the following app:
Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.

**_ITMS-91107: Invalid tracking information** - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/AppMetricaCore.framework/AppMetricaCore.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in any privacy manifest must be valid. For more details, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk._

Пробовали добавить изменения в Privacy-manifest приложения - результата это не принесло, получаем письмо с теми же претензиями

Код манифеста
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTrackingDomains</key>
	<array>
		<string>tracking.appmetrica.yandex.net</string>
		<string>tracking.reserve.appmetrica.yandex.net</string>
	</array>
	<key>NSPrivacyTracking</key>
	<true/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryDiskSpace</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>E174.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>3B52.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryUserDefaults</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>CA92.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategorySystemBootTime</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>35F9.1</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
```

Подскажите, пожалуйста, что мы делаем не так? Или, возможно, нужны изменения с вашей стороны?

**Comment by ziqq** [comment]
I have this same issue.

>A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/AppMetricaCore.framework/AppMetricaCore.bundle/PrivacyInfo.xcprivacy”.

@lighthead9288, тут же все сказано, нужны доработки с их стороны.

**Comment by Sv1phvrAe0n** [comment]
**Появилась такая же проблема.**

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in your app’s privacy manifests must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

Though you are not required to fix the following issues, we wanted to make you aware of them:

ITMS-91107: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “AppMetricaCore.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in any privacy manifest must be valid. For more details, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

Добавили в PrivacyInfo.xcprivacy код
```
	<key>NSPrivacyTracking</key>
	<true/>
	<key>NSPrivacyTrackingDomains</key>
        <array>
            <string>tracking.appmetrica.yandex.net</string>
            <string>tracking.reserve.appmetrica.yandex.net</string>
        </array>
```
        
но и это не помогло. Раньше все было ок и файл PrivacyInfo.xcprivacy не менялся уже на протяжении нескольких релизов

**Comment by snoopdoggy322** [comment]
Та же проблема

**Comment by Amavy** [comment]
В версии 3.0.0 проблема есть. 
В нативном плагине эта же проблема, общают в течении нескольких дней выкатить фикс
https://github.com/appmetrica/appmetrica-sdk-ios/issues/20
В целом я как понимаю можно будет после раскатки фикса обновить поды и проблема исчезнет.

**Comment by Amavy** [comment]
Обновите пожалуйста плагин, в нативной части исправили ошибку

**Comment by KondratyonokNikita** [comment]
The issue with the native dependency was fixed in version 5.8.0 (https://github.com/appmetrica/appmetrica-sdk-ios/releases/tag/5.8.0). Please update the plugin to version 3.1.0.
