### ISSUE TITLE
NSPrivacyTracking

### ISSUE THREAD

**Issue by antonrykov** [appmetrica/appmetrica-flutter-plugin#7]
Использую версию плагина 3.0.0.
При деплое приложения в appStore получил следующий ответ
![photo_2024-10-17_17-34-46](https://github.com/user-attachments/assets/be719c88-649c-4063-8a1d-fa36605cc56c)

**Comment by NesterovichAlexey** [comment]
Duplicate of https://github.com/appmetrica/appmetrica-flutter-plugin/issues/2
